### ISSUE TITLE
Top menu Dropdown in demo site not working

### ISSUE THREAD

**Issue by avra911** [mkhairi/materialize-rails#11]
Hi,

The top menu dropdown after the user is logged in is not working in http://materialize.labs.my/ demo website. There should be 2 links: profile and logout, but instead, the page is refreshed when the trigger is clicked. 

I think the class name should be `dropdown-trigger`, not `dropdown-button`.

The dropdown menus from the left sidebar are working.

**Comment by mkhairi** [comment]
fixed 👍
